include_recipe 'relint::acceptance_tests'
include_recipe 'relint::bosh_directors'
include_recipe 'relint::concourse_cli'
include_recipe 'relint::fast_bosh'
include_recipe 'relint::spiff'
include_recipe 'relint::vim_luan'
include_recipe 'relint::pullify'
